version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    volumes:
      - ./data/gitea:/data
    expose:
      - "3000"
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    expose:
      - "3000"
    networks:
      - internal

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - ./authelia/config:/config
    expose:
      - "9091"
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/site-confs:/etc/nginx/conf.d
      - ./nginx/proxy-confs:/config/nginx/proxy-confs
    depends_on:
      - gitea
      - grafana
      - authelia
    networks:
      - internal

networks:
  internal:
    driver: bridge
